//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: echo.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


///
/// This is a simple RPC service. It's like an interface declaration in the Protobuf language. In my opinion, it's more
/// useful to think of this as an interface and not a service.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol EchoProvider: CallHandlerProvider {
  var interceptors: EchoServerInterceptorFactoryProtocol? { get }

  ///
  /// This is a simple RPC method that echos back some message. Well, it's not really a method but rather the interface
  /// of a method. It's up to the implementing server-side code to actually implement the echo functionality. There's
  /// nothing stopping the server-side implementation from just returning a random string or an empty string instead of
  /// actually echoing back the same string.
  func echo(request: Message, context: StatusOnlyCallContext) -> EventLoopFuture<Message>
}

extension EchoProvider {
  public var serviceName: Substring {
    return EchoServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Echo":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message>(),
        responseSerializer: ProtobufSerializer<Message>(),
        interceptors: self.interceptors?.makeEchoInterceptors() ?? [],
        userFunction: self.echo(request:context:)
      )

    default:
      return nil
    }
  }
}

#if compiler(>=5.6)

///
/// This is a simple RPC service. It's like an interface declaration in the Protobuf language. In my opinion, it's more
/// useful to think of this as an interface and not a service.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol EchoAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: EchoServerInterceptorFactoryProtocol? { get }

  ///
  /// This is a simple RPC method that echos back some message. Well, it's not really a method but rather the interface
  /// of a method. It's up to the implementing server-side code to actually implement the echo functionality. There's
  /// nothing stopping the server-side implementation from just returning a random string or an empty string instead of
  /// actually echoing back the same string.
  @Sendable func echo(
    request: Message,
    context: GRPCAsyncServerCallContext
  ) async throws -> Message
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension EchoAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return EchoServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return EchoServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: EchoServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Echo":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message>(),
        responseSerializer: ProtobufSerializer<Message>(),
        interceptors: self.interceptors?.makeEchoInterceptors() ?? [],
        wrapping: self.echo(request:context:)
      )

    default:
      return nil
    }
  }
}

#endif // compiler(>=5.6)

public protocol EchoServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'echo'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeEchoInterceptors() -> [ServerInterceptor<Message, Message>]
}

public enum EchoServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Echo",
    fullName: "Echo",
    methods: [
      EchoServerMetadata.Methods.echo,
    ]
  )

  public enum Methods {
    public static let echo = GRPCMethodDescriptor(
      name: "Echo",
      path: "/Echo/Echo",
      type: GRPCCallType.unary
    )
  }
}
